### ISSUE TITLE
background page enhancement

### ISSUE THREAD

**Issue by ridsuteri** [ridsuteri/chatte-R#1]
enhance page design by adding suitable gradient/background image

**Comment by 96RadhikaJadhav** [comment]
@ridsuteri  I would like to take up this issue also.

**Comment by ridsuteri** [comment]
sure @96RadhikaJadhav go ahead with it

**Comment by eeealesha** [comment]
Hello, how can I participate?

**Comment by ridsuteri** [comment]
@eeealesha yes you can

**Comment by ridsuteri** [comment]
@96RadhikaJadhav try to come up with a PR in 3-4 days
