### ISSUE TITLE
Add Issue And PR Tempaltes

### ISSUE THREAD

**Issue by muthuannamalai12** [ridsuteri/chatte-R#13]
Would like to add issue and pr templates to these project that will basically explain the type of issue and its description and also the type of pr the set of checklist that it obeys and its description

Kindly assign this to me as a part of Cross-Woc. I would love to do it

**Comment by ridsuteri** [comment]
great @muthuannamalai12

**Comment by kanak22** [comment]
Can I work on this ? I would like to add these two templates. kindly assign it to me.

**Comment by ridsuteri** [comment]
yes @kanak22 go ahead
