### ISSUE TITLE
I will add name and photo of maintainer in the end of readme file of your repo

### ISSUE THREAD

**Issue by yashlikescode** [ridsuteri/chatte-R#18]
like the one mentioned below
![image](https://user-images.githubusercontent.com/66861659/110196870-6969ab80-7e6d-11eb-9960-4ec4725fe0aa.png)

**Comment by ridsuteri** [comment]
@kmryashasvi yes go ahead with  it ..also attach screenshot along with the PR

**Comment by yashlikescode** [comment]
Can I close this issue now?

**Comment by ridsuteri** [comment]
yea
