### ISSUE TITLE
add hover effect over buttons

### ISSUE THREAD

**Issue by ridsuteri** [ridsuteri/chatte-R#2]
add hover effect using css on buttons and text areas

**Comment by 96RadhikaJadhav** [comment]
@ridsuteri  Can you please assign this issue to me? I'm crossWoc participant.

**Comment by ridsuteri** [comment]
sure @96RadhikaJadhav

**Comment by ridsuteri** [comment]
@96RadhikaJadhav try to get this done in 3-4 days
