### ISSUE TITLE
send button is not properly aligned/located

### ISSUE THREAD

**Issue by pranabprohit** [ridsuteri/chatte-R#23]
###Description
There no space between send button and text area in chat.html.

###Screenshot
![image](https://user-images.githubusercontent.com/53513600/110839147-43a73100-82c9-11eb-92cc-dd896541a629.png)

**Comment by pranabprohit** [comment]
Hii @ridsuteri, I would like to work on this issue as a part of CWOC. Can you please assign this issue to me.

**Comment by ridsuteri** [comment]
Ok @pranabprohit go ahead
