### ISSUE TITLE
PR template needs to be updated

### ISSUE THREAD

**Issue by pranabprohit** [ridsuteri/chatte-R#25]
**Describe the bug**
There is few points repeating and minor spelling mistake in PR template like additional info, related issue, type of change, description etc are repeating.

**Screenshots**
![image](https://user-images.githubusercontent.com/53513600/111034763-298e5f80-843d-11eb-89aa-7b0f955f6a62.png)

**Comment by pranabprohit** [comment]
Hello @ridsuteri, I would like to work on this issue as a part of CWOC.

**Comment by ridsuteri** [comment]
@pranabprohit can u highlight the changes u are willing to make?

**Comment by pranabprohit** [comment]
sure @ridsuteri 

> @pranabprohit can u highlight the changes u are willing to make?

![pr template](https://user-images.githubusercontent.com/53513600/111036416-18495100-8445-11eb-9f19-c85d358daee7.png)

![pr template1](https://user-images.githubusercontent.com/53513600/111036417-18495100-8445-11eb-9c4d-34203ad02f9b.png)

This points are repeating in PR template. So I want to remove those repeating points. As every time we make PR we have to remove it again and again.

**Comment by ridsuteri** [comment]
ok @pranabprohit go ahead
