### ISSUE TITLE
add a landing page to the web application

### ISSUE THREAD

**Issue by ridsuteri** [ridsuteri/chatte-R#3]
add a  attractive landing page with name of application and some greeting message

**Comment by soumya-badkul** [comment]
Hey, can I work on this issue @ridsuteri ?

**Comment by ridsuteri** [comment]
yes @soumya-badkul go ahead with it,also try to get this done in 3-4 days else this will be allocated to someone else

**Comment by soumya-badkul** [comment]
Okay thanks

**Comment by soumya-badkul** [comment]
Hey @ridsuteri , please go through the videos and let me know which page works for you. Il go ahead with it :)
https://drive.google.com/drive/folders/1fG0_05wyb0dGHtfO1QYMQCUkI7-EBA5H?usp=sharing

**Comment by ridsuteri** [comment]
@soumya-badkul the second one(that with santa clause) looks cool
